function bezier2ndDerivCoeffs = returnBezier2ndDerivCubic(t)

 bezier2ndDerivCoeffs = [...
     (6 * (1 - t)),...
      ( -2*(6*(1 - t)) +  (6*t) ), ...
     ( 6*(1 - t) + (-2 * (6 * t)) ),...
     (6 * t),...
     ];

end
