function bezierDerivCoeffs3P = returnBezier3P_sL_incline_DerivEval_dsL(phase,stepLength,incline)

inclineFuncs = returnBezierLinear(incline);
 stepLengthFuncs = returnBezierDerivQuadratic(stepLength);
 phaseFuncs = returnBezierCubic(phase);
 
 numInclineFuncs = length(inclineFuncs);
 numStepLengthFuncs = length(stepLengthFuncs);
 numPhaseFuncs = length(phaseFuncs);
    
 bezierDerivCoeffs3P = zeros(1,numInclineFuncs*numStepLengthFuncs*numPhaseFuncs);
 N=1;
 for ii = 1:numInclineFuncs
     inclineFunc = inclineFuncs(ii);
     
     for jj = 1:numStepLengthFuncs
         stepLengthFunc = stepLengthFuncs(jj);
         
         for kk = 1:numPhaseFuncs
             phaseFunc = phaseFuncs(kk);
             bezierDerivCoeffs3P(N) = inclineFunc * stepLengthFunc * phaseFunc;
             N = N + 1;
         end
         
     end
     
 end
 
 
%  bezierDerivCoeffs3P = [(incline).*1.*(1-phase).^3,...
%      (incline).*1.*3*(1-phase).^2.*phase,...
%      (incline).*1.*3*(1-phase).*(phase).^2,...
%      (incline).*1.*(phase).^3,...
%      (incline).*(-1).*(1-phase).^3,...
%      (incline).*(-1).*3*(1-phase).^2.*phase,...
%      (incline).*(-1).*3*(1-phase).*(phase).^2,...
%      (incline).*(-1).*(phase).^3,...
%      (1 - incline).*1.*(1-phase).^3,...
%      (1 - incline).*1.*3*(1-phase).^2.*phase,...
%      (1 - incline).*1.*3*(1-phase).*(phase).^2,...
%      (1 - incline).*1.*(phase).^3,...
%      (1 - incline).*(-1).*(1-phase).^3,...
%      (1 - incline).*(-1).*3*(1-phase).^2.*phase,...
%      (1 - incline).*(-1).*3*(1-phase).*(phase).^2,...
%      (1 - incline).*(-1).*(phase).^3];

end